apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.fullname" . }}-namesrv-hl
  labels:
    app: namesrv
    app.kubernetes.io/component: namesrv
    app.kubernetes.io/name: {{ include "rocketmq.name" . }}
    helm.sh/chart: {{ include "rocketmq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: rocketmq
  selector:
    app: namesrv
    app.kubernetes.io/component: namesrv
    app.kubernetes.io/name: {{ include "rocketmq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.fullname" . }}-dashboard-hl
  labels:
    app: dashboard
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/name: {{ include "rocketmq.name" . }}
    helm.sh/chart: {{ include "rocketmq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: dashboard
  selector:
    app: dashboard
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/name: {{ include "rocketmq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-cluster-dashboard-service
  namespace: iot
spec:
  selector:
    app: dashboard
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/name: {{ include "rocketmq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: dashboard
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
